import Head from "next/head";
import Hero from "../components/Hero";
import Instagram from "../components/Instagram";
import Slider from "../components/Slider";
import { SliderData } from "../components/SliderData";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Photograpy Next App</title>
				<meta name="description" content="Generated by next app" />
				<link rel="icon" href="/favicon.co" />
			</Head>

			<Hero
				heading="Capture Photography"
				message="I Capture a Moments in Nature and Keep Them Alive."
			/>
			<Slider slides={SliderData} />
			<Instagram />
		</div>
	);
}
